/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FriendManagement;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import ContentCreation.Message;
import ContentCreation.Profile;

/**
 *
 * @author dandy
 */
public class FriendRequestsPage extends javax.swing.JDialog {

    private Profile user;
    private int iterator;
    /**
     * Creates new form FriendRequestsPage
     */
    
     private JSONArray friendRequestsArray;
     public FriendRequestsPage(java.awt.Frame parent, boolean modal,Profile user) {
        super(parent, modal);
        this.user = user;
        this.friendRequestsArray = user.getFriendsRequests();
        this.iterator = 0;
        initComponents();
        showFriendRequests(this.iterator);
    }
    public FriendRequestsPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Accept = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Accept.setText("Accept");
        Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Remove)
                .addGap(43, 43, 43)
                .addComponent(Accept)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Back)
                        .addGap(235, 235, 235)
                        .addComponent(Next))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accept)
                    .addComponent(Remove))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addComponent(Next)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showFriendRequests(int iterator){
        String text = "";
        try{
            if(((String)(((JSONObject)friendRequestsArray.get(iterator)).get("Request Status"))).compareTo("Pending")==0){
        text = text + ((String)(((JSONObject)friendRequestsArray.get(iterator)).get("Profile Username")))+"\n\n";
            }
        }catch(IndexOutOfBoundsException e){}
        jLabel1.setText(text);
    }
    
    private void AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptActionPerformed
        JSONObject fr =(JSONObject) (this.friendRequestsArray.get(this.iterator));//get friend request
        FriendRequests friendRequests =new FriendRequests((String)fr.get("Request Status"), (String)fr.get("Profile Id"), user.getUserId());
        friendRequests.acceptFriendRequestStatus();
        Message m = new Message(null,true,"Friend Request accepted");
        m.setLocationRelativeTo(this);
        m.setVisible(true);
        this.iterator =0;
    }//GEN-LAST:event_AcceptActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        JSONObject fr =(JSONObject) (this.friendRequestsArray.get(this.iterator));//get friend request
        FriendRequests friendRequests =new FriendRequests((String)fr.get("Request Status"), (String)fr.get("Profile Id"), user.getUserId());
        friendRequests.removeFriendRequestStatus();
        Message m = new Message(null,true,"Friend Request Removed");
        m.setLocationRelativeTo(this);
        m.setVisible(true);
        this.iterator = 0;
    }//GEN-LAST:event_RemoveActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        if(this.friendRequestsArray.size()!=0){
        this.iterator = (this.iterator-1)%this.friendRequestsArray.size();
        showFriendRequests(this.iterator);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if(this.friendRequestsArray.size()!=0){
        this.iterator = (this.iterator+1)%this.friendRequestsArray.size();
        showFriendRequests(this.iterator);
        }
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendRequestsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendRequestsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendRequestsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendRequestsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FriendRequestsPage dialog = new FriendRequestsPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accept;
    private javax.swing.JButton Back;
    private javax.swing.JButton Next;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
